name: ResolveAI CI

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  backend:
    name: Backend Tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: backend/package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
        env:
          JWT_ACCESS_SECRET: ${{ secrets.JWT_ACCESS_SECRET }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
          Gemini_Api_Key: ${{ secrets.Gemini_Api_Key }}

  frontend:
    name: Frontend Tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Build frontend
        run: npm run build